services:
  postgres:
    container_name: pg-database
    image: postgres:17
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
  # backend:
  #   container_name: backend
  #   build:
  #     context: backend/
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - postgres
  #   links:
  #     - postgres
  # frontend:
  #   container_name: frontend
  #   build:
  #     context: frontend/
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - backend
  #   links:
  #     - backend

volumes:
  pgdata:
