spring:
  application:
    name: twentyfortyeight-backend
  datasource:
    driver: org.postgresql.Driver
    url:  jdbc:postgresql://localhost:5432/postgres
    username: pguser
    password: pgpassword

  jpa:
    hibernate:
      ddl-auto: update
